### ISSUE TITLE
error running - bundle exec rake spec

### ISSUE THREAD

**Issue by betht1220** [cloudfoundry/cf-mysql-broker#17]
1. I ran into permission issue with command = bundle exec rake db:setup, so I set the pw for root
    in config/database.yml with the new root password. This allows me to run db:setup w/o error
2. when I run bundle exec rake spec, got the following error.
    Looking at the errors, it seems that mysql.user table does not have the user "K0KWTDuo23o21X0b", and also the table mysql.user does not have "password" column.

I tried to look closer, but I'm not familiar with ruby code (I've spent some time fixing my ruby version), and I do not want to mess up my setup any further.

Can you please give me some help.

What I want to do is to register your broker with CF environment, and see how the
SSO works with dashboard.

Thank you so much for help, I really, really appreciate this.

Sincerely
Beth Tran

Randomized with seed 42152
.......................................................................................................................................................................................F.FF.

Failures:

  1) ServiceBinding#save sets the max connections to the value specified by the plan
     Failure/Error: expect(connection.select_values("SHOW GRANTS FOR #{username}")[0]).to include(max_user_connection_sql)
       expected "GRANT USAGE ON *.* TO 'K0KWTDuo23o21X0b'@'%'" to include "WITH MAX_USER_CONNECTIONS 12"
     # ./spec/models/service_binding_spec.rb:199:in `block (3 levels) in <top (required)>'

  2) ServiceBinding#save creates a user with a random password
     Failure/Error: connection.select_values(password_sql).count

     ActiveRecord::StatementInvalid:
       Mysql2::Error: Unknown column 'password' in 'where clause': SELECT * FROM mysql.user WHERE user = 'K0KWTDuo23o21X0b' AND password = PASSWORD('randompassword')
     # ./spec/models/service_binding_spec.rb:180:in `block (4 levels) in <top (required)>'
     # ./spec/models/service_binding_spec.rb:176:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Mysql2::Error:
     #   Unknown column 'password' in 'where clause'
     #   ./spec/models/service_binding_spec.rb:180:in `block (4 levels) in <top (required)>'

  3) ServiceBinding#save raises an error when creating the same user twice
     Failure/Error: expect(connection.select_values(password_sql).count).to eq(1)

     ActiveRecord::StatementInvalid:
       Mysql2::Error: Unknown column 'password' in 'where clause': SELECT * FROM mysql.user WHERE user = 'K0KWTDuo23o21X0b' AND password = PASSWORD('randompassword')
     # ./spec/models/service_binding_spec.rb:210:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Mysql2::Error:
     #   Unknown column 'password' in 'where clause'
     #   ./spec/models/service_binding_spec.rb:210:in `block (3 levels) in <top (required)>'

Finished in 8.26 seconds (files took 1.55 seconds to load)
188 examples, 3 failures

Failed examples:

rspec ./spec/models/service_binding_spec.rb:195 # ServiceBinding#save sets the max connections to the value specified by the plan
rspec ./spec/models/service_binding_spec.rb:175 # ServiceBinding#save creates a user with a random password
rspec ./spec/models/service_binding_spec.rb:202 # ServiceBinding#save raises an error when creating the same user twice

**Comment by betht1220** [comment]
I've resolved this issue using mysql56 as documented in README.
Thanks
Beth Tran
