### ISSUE TITLE
cf-mysql-broker/0 is failing with quota-enforcer

### ISSUE THREAD

**Issue by kamoljan** [cloudfoundry/cf-mysql-broker#20]
Hi guys!

`cf-mysql-broker/0` instance is failing with the following error:
```
# tail -f /var/vcap/sys/log/cf-mysql-broker/db_migrate.combined.log
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/var/vcap/packages/ruby/bin/bundle:22:in `load'
/var/vcap/packages/ruby/bin/bundle:22:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
Migrations failed at Mon Sep 11 14:58:13 UTC 2017
#<Mysql2::Error: Lost connection to MySQL server at 'handshake: waiting for inital communication packet', system error: 110>
Couldn't create database for {"adapter"=>"mysql2", "encoding"=>"utf8", "database"=>"mysql_broker", "pool"=>5, "connect_timeout"=>20, "read_timeout"=>20, "reconnect"=>true, "host"=>"mysql-proxy.platform.dev.jp.XXX.org", "port"=>3306, "username"=>"cf-mysql-broker", "password"=>"XXX"}, {:charset=>"utf8", :collation=>"utf8_unicode_ci"}
(If you set the charset manually, make sure you have a matching collation)


rake aborted!
Mysql2::Error: Lost connection to MySQL server at 'handshake: waiting for inital communication packet', system error: 110
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:87:in `connect'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:87:in `initialize'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_connection'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_handling.rb:87:in `connection'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:916:in `initialize'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:823:in `new'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:823:in `up'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:801:in `migrate'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/var/vcap/packages/ruby/bin/bundle:22:in `load'
/var/vcap/packages/ruby/bin/bundle:22:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
Migrations failed at Mon Sep 11 14:59:24 UTC 2017
#<Mysql2::Error: Lost connection to MySQL server at 'handshake: waiting for inital communication packet', system error: 110>
Couldn't create database for {"adapter"=>"mysql2", "encoding"=>"utf8", "database"=>"mysql_broker", "pool"=>5, "connect_timeout"=>20, "read_timeout"=>20, "reconnect"=>true, "host"=>"mysql-proxy.platform.dev.jp.XXX.org", "port"=>3306, "username"=>"cf-mysql-broker", "password"=>"XXX"}, {:charset=>"utf8", :collation=>"utf8_unicode_ci"}
(If you set the charset manually, make sure you have a matching collation)
rake aborted!
```

It is on ERT 1.11.11 and OpsMan 1.11.10.

**Comment by kamoljan** [comment]
Any update mr. @cf-gitbot ? :)

**Comment by menicosia** [comment]
@kamoljan sorry we weren't able to help on this. I wish I'd noticed earlier that your issue is on Pivotal Cloud Foundry. For that, you can file a support ticket at https://support.pivotal.io/

Let me know if there's anything we can do to make this sort of problem go easier!

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.
